In [2]:
import numpy as np 
import matplotlib.pyplot as plt
import pandas as pd
import sklearn

print(sklearn.__version__)

1.7.1

In [3]:
import pandas as pd 

heart_disease = pd.read_csv("./data/heart-disease.csv")
heart_disease

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [4]:
X = heart_disease.drop("target", axis=1)
y = heart_disease["target"]
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [5]:
y.head() , y.value_counts()

(0    1
 1    1
 2    1
 3    1
 4    1
 Name: target, dtype: int64,
 target
 1    165
 0    138
 Name: count, dtype: int64)

In [6]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

((227, 13), (76, 13), (227,), (76,))

In [7]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()
clf.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [8]:
clf.fit(X_train, y_train)

RandomForestClassifier()

In [9]:
y_label = clf.predict(np.array([0,2,3,4]))

/home/lenovo/Documents/ml_dl_frame_work/.venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

ValueError: Expected 2D array, got 1D array instead:
array=[0. 2. 3. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [ ]:

y_preds = clf.predict(X_test)

In [ ]:
train_acc = clf.score(X_train, y_train)
test_acc = clf.score(X_test, y_test)
print(f"Train acc: {train_acc*100:.2f}%")
print(f"Test acc: {test_acc*100:.2f}% ")

Train acc: 100.00%
Test acc: 84.21%

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(classification_report(y_test, y_preds))

              precision    recall  f1-score   support

           0       0.76      0.90      0.82        31
           1       0.92      0.80      0.86        45

    accuracy                           0.84        76
   macro avg       0.84      0.85      0.84        76
weighted avg       0.86      0.84      0.84        76

In [ ]:
conf_mat = confusion_matrix(y_test, y_preds)
conf_mat

array([[28,  3],
       [ 9, 36]])

In [ ]:
accuracy_score(y_test, y_preds)

0.8421052631578947

In [ ]:
np.random.seed(42)
for i  in range(100,500,10):
    print(f"Trying model with {i} estimators ...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)
    print(f"Model accuracy on test set {i}: {model.score(X_test,y_test)*100:.2f}%")

Trying model with 100 estimators ...
Model accuracy on test set 100: 82.89%
Trying model with 110 estimators ...
Model accuracy on test set 110: 86.84%
Trying model with 120 estimators ...
Model accuracy on test set 120: 80.26%
Trying model with 130 estimators ...
Model accuracy on test set 130: 88.16%
Trying model with 140 estimators ...
Model accuracy on test set 140: 86.84%
Trying model with 150 estimators ...
Model accuracy on test set 150: 86.84%
Trying model with 160 estimators ...
Model accuracy on test set 160: 86.84%
Trying model with 170 estimators ...
Model accuracy on test set 170: 86.84%
Trying model with 180 estimators ...
Model accuracy on test set 180: 84.21%
Trying model with 190 estimators ...
Model accuracy on test set 190: 86.84%
Trying model with 200 estimators ...
Model accuracy on test set 200: 88.16%
Trying model with 210 estimators ...
Model accuracy on test set 210: 84.21%
Trying model with 220 estimators ...
Model accuracy on test set 220: 88.16%
Trying model with 230 estimators ...
Model accuracy on test set 230: 84.21%
Trying model with 240 estimators ...
Model accuracy on test set 240: 85.53%
Trying model with 250 estimators ...
Model accuracy on test set 250: 84.21%
Trying model with 260 estimators ...
Model accuracy on test set 260: 85.53%
Trying model with 270 estimators ...
Model accuracy on test set 270: 85.53%
Trying model with 280 estimators ...
Model accuracy on test set 280: 85.53%
Trying model with 290 estimators ...
Model accuracy on test set 290: 85.53%
Trying model with 300 estimators ...
Model accuracy on test set 300: 86.84%
Trying model with 310 estimators ...
Model accuracy on test set 310: 86.84%
Trying model with 320 estimators ...
Model accuracy on test set 320: 85.53%
Trying model with 330 estimators ...
Model accuracy on test set 330: 85.53%
Trying model with 340 estimators ...
Model accuracy on test set 340: 86.84%
Trying model with 350 estimators ...
Model accuracy on test set 350: 85.53%
Trying model with 360 estimators ...
Model accuracy on test set 360: 85.53%
Trying model with 370 estimators ...
Model accuracy on test set 370: 85.53%
Trying model with 380 estimators ...
Model accuracy on test set 380: 85.53%
Trying model with 390 estimators ...
Model accuracy on test set 390: 85.53%
Trying model with 400 estimators ...
Model accuracy on test set 400: 89.47%
Trying model with 410 estimators ...
Model accuracy on test set 410: 85.53%
Trying model with 420 estimators ...
Model accuracy on test set 420: 85.53%
Trying model with 430 estimators ...
Model accuracy on test set 430: 84.21%
Trying model with 440 estimators ...
Model accuracy on test set 440: 86.84%
Trying model with 450 estimators ...
Model accuracy on test set 450: 86.84%
Trying model with 460 estimators ...
Model accuracy on test set 460: 85.53%
Trying model with 470 estimators ...
Model accuracy on test set 470: 85.53%
Trying model with 480 estimators ...
Model accuracy on test set 480: 86.84%
Trying model with 490 estimators ...
Model accuracy on test set 490: 86.84%

In [ ]:
from sklearn.model_selection import cross_val_score

np.random.seed(42)
for i in range (100,500,10):
    print(f"Trying Model with {i} estimator...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train,y_train)


    model_score = model.score(X_test,y_test)
    print(f"MOdel accuracy on single test set split: {model_score*100:.2f}%")

    cross_val_mean = np.mean(cross_val_score(model,X,y,cv=5))
    print(f"5-fold cross-validation score : {cross_val_mean*100:.2f}%")

    print("")

Trying Model with 100 estimator...
MOdel accuracy on single test set split: 82.89%
5-fold cross-validation score : 82.15%

Trying Model with 110 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 81.17%

Trying Model with 120 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 83.16%

Trying Model with 130 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 83.14%

Trying Model with 140 estimator...
MOdel accuracy on single test set split: 80.26%
5-fold cross-validation score : 82.48%

Trying Model with 150 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 80.17%

Trying Model with 160 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 80.83%

Trying Model with 170 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 81.83%

Trying Model with 180 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 81.50%

Trying Model with 190 estimator...
MOdel accuracy on single test set split: 89.47%
5-fold cross-validation score : 81.83%

Trying Model with 200 estimator...
MOdel accuracy on single test set split: 82.89%
5-fold cross-validation score : 82.17%

Trying Model with 210 estimator...
MOdel accuracy on single test set split: 84.21%
5-fold cross-validation score : 81.16%

Trying Model with 220 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 81.83%

Trying Model with 230 estimator...
MOdel accuracy on single test set split: 89.47%
5-fold cross-validation score : 82.49%

Trying Model with 240 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.49%

Trying Model with 250 estimator...
MOdel accuracy on single test set split: 82.89%
5-fold cross-validation score : 81.83%

Trying Model with 260 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.49%

Trying Model with 270 estimator...
MOdel accuracy on single test set split: 82.89%
5-fold cross-validation score : 81.83%

Trying Model with 280 estimator...
MOdel accuracy on single test set split: 88.16%
5-fold cross-validation score : 82.48%

Trying Model with 290 estimator...
MOdel accuracy on single test set split: 84.21%
5-fold cross-validation score : 83.48%

Trying Model with 300 estimator...
MOdel accuracy on single test set split: 84.21%
5-fold cross-validation score : 81.84%

Trying Model with 310 estimator...
MOdel accuracy on single test set split: 84.21%
5-fold cross-validation score : 81.50%

Trying Model with 320 estimator...
MOdel accuracy on single test set split: 82.89%
5-fold cross-validation score : 80.17%

Trying Model with 330 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 81.17%

Trying Model with 340 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.16%

Trying Model with 350 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.15%

Trying Model with 360 estimator...
MOdel accuracy on single test set split: 88.16%
5-fold cross-validation score : 81.15%

Trying Model with 370 estimator...
MOdel accuracy on single test set split: 84.21%
5-fold cross-validation score : 81.49%

Trying Model with 380 estimator...
MOdel accuracy on single test set split: 88.16%
5-fold cross-validation score : 82.81%

Trying Model with 390 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 81.15%

Trying Model with 400 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.16%

Trying Model with 410 estimator...
MOdel accuracy on single test set split: 85.53%
5-fold cross-validation score : 80.83%

Trying Model with 420 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.49%

Trying Model with 430 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.16%

Trying Model with 440 estimator...
MOdel accuracy on single test set split: 88.16%
5-fold cross-validation score : 82.48%

Trying Model with 450 estimator...
MOdel accuracy on single test set split: 86.84%
5-fold cross-validation score : 82.81%

Trying Model with 460 estimator...
MOdel accuracy on single test set split: 84.21%
5-fold cross-validation score : 81.83%

Trying Model with 470 estimator...
MOdel accuracy on single test set split: 89.47%
5-fold cross-validation score : 82.15%

Trying Model with 480 estimator...
MOdel accuracy on single test set split: 88.16%
5-fold cross-validation score : 83.47%

Trying Model with 490 estimator...
MOdel accuracy on single test set split: 88.16%
5-fold cross-validation score : 82.81%

In [ ]:
np.random.seed(42)

from sklearn.model_selection import GridSearchCV

param_grid = {'n_estimators': [i for i in range(100,500,10)]}

grid= GridSearchCV(estimator=RandomForestClassifier(), param_grid=param_grid,cv=5,verbose =1)


grid.fit(X,y)
print(f"the best parameter values are : {grid.best_params_}")
print(f"WIth a score of :{grid.best_score_*100:.2f}%")

Fitting 5 folds for each of 40 candidates, totalling 200 fits
the best parameter values are : {'n_estimators': 470}
WIth a score of :83.48%

In [ ]:
clf = grid.best_estimator_
clf

RandomForestClassifier(n_estimators=470)

In [ ]:
clf =clf.fit(X_train,y_train)
print(f"Best model score on single split of the data : {clf.score(X_test,y_test)*100:.2f}%")

Best model score on single split of the data : 82.89%

In [ ]:
import pickle

pickle.dump(model,open("random_forest_model_1.pkl" , "wb"))

In [ ]:
loaded_pickle_model = pickle.load(open("random_forest_model_1.pkl","rb"))
print(f"Loaded pickle model predicition score : {loaded_pickle_model.score(X_test,y_test)*100:.2f}%")

Loaded pickle model predicition score : 88.16%

In [ ]:
from joblib import dump, load

# Save a model using joblib
dump(model, "random_forest_model_1.joblib")

['random_forest_model_1.joblib']

In [ ]:
loaded_joblib_model = load("random_forest_model_1.joblib")
print(f"Loaded joblib model prediction score :{loaded_joblib_model.score(X_test,y_test)*100:.2f}%")

Loaded joblib model prediction score :88.16%

In [ ]:
heart_disease.head()
X = heart_disease.drop('target' , axis =1)
y = heart_disease['target']
X , y

(     age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
 0     63    1   3       145   233    1        0      150      0      2.3
 1     37    1   2       130   250    0        1      187      0      3.5
 2     41    0   1       130   204    0        0      172      0      1.4
 3     56    1   1       120   236    0        1      178      0      0.8
 4     57    0   0       120   354    0        1      163      1      0.6
 ..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...
 298   57    0   0       140   241    0        1      123      1      0.2
 299   45    1   3       110   264    0        1      132      0      1.2
 300   68    1   0       144   193    1        1      141      0      3.4
 301   57    1   0       130   131    0        1      115      1      1.2
 302   57    0   1       130   236    0        0      174      0      0.0

      slope  ca  thal
 0        0   0     1
 1        0   0     2
 2        2   0     2
 3        2   0     2
 4        2   0     2
 ..     ...  ..   ...
 298      1   0     3
 299      1   0     3
 300      1   2     3
 301      1   1     3
 302      1   1     2

 [303 rows x 13 columns],
 0      1
 1      1
 2      1
 3      1
 4      1
       ..
 298    0
 299    0
 300    0
 301    0
 302    0
 Name: target, Length: 303, dtype: int64)

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((242, 13), (61, 13), (242,), (61,))

In [ ]:
X.shape[0]*0.8

242.4

In [ ]:
X.shape[0]*0.2

60.6

In [ ]:
car_sales = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended.csv") # load data directly from raw URL (source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/car-sales-extended.csv
car_sales

       Make Colour  Odometer (KM)  Doors  Price
0     Honda  White          35431      4  15323
1       BMW   Blue         192714      5  19943
2     Honda  White          84714      4  28343
3    Toyota  White         154365      4  13434
4    Nissan   Blue         181577      3  14043
..      ...    ...            ...    ...    ...
995  Toyota  Black          35820      4  32042
996  Nissan  White         155144      3   5716
997  Nissan   Blue          66604      4  31570
998   Honda  White         215883      4   4001
999  Toyota   Blue         248360      4  12732

[1000 rows x 5 columns]

In [ ]:
car_sales.dtypes

Make             object
Colour           object
Odometer (KM)     int64
Doors             int64
Price             int64
dtype: object

In [ ]:
X = car_sales.drop('Price', axis=1)
y = car_sales['Price']
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [ ]:
from sklearn.ensemble import RandomForestRegressor

model = RandomForestRegressor
model.fit(X_train,y_train)
model.score(X_test,y_test)

AttributeError: 'DataFrame' object has no attribute '_validate_params'

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = [ "Make","Colour","Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot",
                                  one_hot,
                                  categorical_features)],
                                  remainder="passthrough")

transformed_X = transformer.fit_transform(X)
transformed_X

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [ ]:
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [ ]:
transformed_X[0]

array([0.0000e+00, 1.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
       0.0000e+00, 0.0000e+00, 0.0000e+00, 1.0000e+00, 0.0000e+00,
       1.0000e+00, 0.0000e+00, 3.5431e+04])

In [ ]:
X.iloc[0]

Make             Honda
Colour           White
Odometer (KM)    35431
Doors                4
Name: 0, dtype: object

In [ ]:
categorical_variables= ["Make","Colour","Doors"]
dummies = pd.get_dummies(data=car_sales[categorical_variables])
dummies

,Doors,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White
0,4,False,True,False,False,False,False,False,False,True
1,5,True,False,False,False,False,True,False,False,False
2,4,False,True,False,False,False,False,False,False,True
3,4,False,False,False,True,False,False,False,False,True
4,3,False,False,True,False,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...
995,4,False,False,False,True,True,False,False,False,False
996,3,False,False,True,False,False,False,False,False,True
997,4,False,False,True,False,False,True,False,False,False
998,4,False,True,False,False,False,False,False,False,True
999,4,False,False,False,True,False,True,False,False,False

In [ ]:
# Have to convert doors to object for dummies to work on it...
car_sales["Doors"] = car_sales["Doors"].astype(object)
dummies = pd.get_dummies(data=car_sales[["Make", "Colour", "Doors"]],
                         dtype=float)
dummies

,Make_BMW,Make_Honda,Make_Nissan,Make_Toyota,Colour_Black,Colour_Blue,Colour_Green,Colour_Red,Colour_White,Doors_3,Doors_4,Doors_5
0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
1,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
4,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...
995,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
996,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
997,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0
998,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
999,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0

In [ ]:
np.random.seed(42)
X_train,X_test, y_train, y_test = train_test_split(transformed_X,
                                                    y,
                                                    test_size=0.2)


model = RandomForestRegressor()


model.fit(X_train, y_train)


model.score(X_test, y_test)

0.3235867221569877

In [ ]:
car_sales_missing = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv")
car_sales_missing.head(10)

     Make Colour  Odometer (KM)  Doors    Price
0   Honda  White        35431.0    4.0  15323.0
1     BMW   Blue       192714.0    5.0  19943.0
2   Honda  White        84714.0    4.0  28343.0
3  Toyota  White       154365.0    4.0  13434.0
4  Nissan   Blue       181577.0    3.0  14043.0
5   Honda    Red        42652.0    4.0  23883.0
6  Toyota   Blue       163453.0    4.0   8473.0
7   Honda  White            NaN    4.0  20306.0
8     NaN  White       130538.0    4.0   9374.0
9   Honda   Blue        51029.0    4.0  26683.0

In [ ]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [ ]:
X_missing = car_sales_missing.drop('Price' , axis =1)
#print(f"NUmber of missing X values : \n{X_missing.isna().sum()}")
y_missing = car_sales_missing["Price"]

In [ ]:

# Let's convert the categorical columns to one hot encoded (code copied from above)
# Turn the categories (Make and Colour) into numbers
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot", 
                                  one_hot, 
                                  categorical_features)],
                                remainder="passthrough",
                                sparse_threshold=0) # return a sparse matrix or not

transformed_X_missing = transformer.fit_transform(X_missing)
transformed_X_missing

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(transformed_X_missing,
                                                    y_missing,
                                                    test_size=0.2)

# Fit and score a model
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

ValueError: Input y contains NaN.

In [ ]:
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [ ]:
car_sales_missing["Make"] = car_sales_missing["Make"].fillna(value="missing")

car_sales_missing["Colour"] = car_sales_missing["Colour"].fillna(value="missing")

In [ ]:
car_sales_missing.isna().sum()

Make              0
Colour            0
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [ ]:
car_sales_missing["Doors"].value_counts()

Doors
4.0    811
5.0     75
3.0     64
Name: count, dtype: int64

In [ ]:
car_sales_missing["Doors"] = car_sales_missing["Doors"].fillna(value=4)

In [ ]:
car_sales_missing["Odometer (KM)"] = car_sales_missing["Odometer (KM)"].fillna(value=car_sales_missing["Odometer (KM)"].mean())

In [ ]:
# Check the number of missing values
car_sales_missing.isna().sum()

Make             0
Colour           0
Odometer (KM)    0
Doors            0
Price            0
dtype: int64

In [ ]:
# Remove rows with missing Price labels
car_sales_missing.dropna(inplace=True)

In [ ]:
len(car_sales_missing)

950

In [ ]:
# Create features
X_missing = car_sales_missing.drop("Price", axis=1)
print(f"Number of missing X values:\n{X_missing.isna().sum()}")

# Create labels
y_missing = car_sales_missing["Price"]
print(f"Number of missing y values: {y_missing.isna().sum()}")

Number of missing X values:
Make             0
Colour           0
Odometer (KM)    0
Doors            0
dtype: int64
Number of missing y values: 0

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

categorical_features = ["Make", "Colour", "Doors"]

one_hot = OneHotEncoder()

transformer = ColumnTransformer([("one_hot", 
                                  one_hot, 
                                  categorical_features)],
                                remainder="passthrough",
                                sparse_threshold=0) # return a sparse matrix or not

transformed_X_missing = transformer.fit_transform(X_missing)
transformed_X_missing

array([[0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 3.54310e+04],
       [1.00000e+00, 0.00000e+00, 0.00000e+00, ..., 0.00000e+00,
        1.00000e+00, 1.92714e+05],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 8.47140e+04],
       ...,
       [0.00000e+00, 0.00000e+00, 1.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 6.66040e+04],
       [0.00000e+00, 1.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.15883e+05],
       [0.00000e+00, 0.00000e+00, 0.00000e+00, ..., 1.00000e+00,
        0.00000e+00, 2.48360e+05]])

In [ ]:
# Split data into training and test sets
np.random.seed(42)
X_train, X_test, y_train, y_test = train_test_split(transformed_X_missing,
                                                    y_missing,
                                                    test_size=0.2)

# Fit and score a model
model = RandomForestRegressor()
model.fit(X_train, y_train)
model.score(X_test, y_test)

0.22011714008302485

In [13]:
# Reimport the DataFrame (so that all the missing values are back)
# car_sales_missing = pd.read_csv("../data/car-sales-extended-missing-data.csv") # read from local directory
car_sales_missing = pd.read_csv("https://raw.githubusercontent.com/mrdbourke/zero-to-mastery-ml/master/data/car-sales-extended-missing-data.csv") # read directly from URL (source: https://github.com/mrdbourke/zero-to-mastery-ml/blob/master/data/car-sales-extended-missing-data.csv)
car_sales_missing.isna().sum()

Make             49
Colour           50
Odometer (KM)    50
Doors            50
Price            50
dtype: int64

In [14]:
car_sales_missing.dropna(subset=["Price"],inplace=True)

In [15]:
car_sales_missing.isna().sum()

Make             47
Colour           46
Odometer (KM)    48
Doors            47
Price             0
dtype: int64

In [17]:
X=car_sales_missing.drop("Price",axis=1)
y=car_sales_missing["Price"]

np.random.seed(42)
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [20]:
from sklearn.impute import SimpleImputer

cat_imputer = SimpleImputer(strategy="constant",fill_value="missing")
door_imputer = SimpleImputer(strategy="constant", fill_value=4)
num_imputer = SimpleImputer(strategy="mean")

In [21]:
categorical_features=["Make","Colour"]
door_feature=["Doors"]
numerical_feature =["Odometer(KM)"]

In [24]:
from sklearn.compose import ColumnTransformer

imputer = ColumnTransformer([
    ("cat_imputer",cat_imputer,categorical_features),
    ("door_imputer",door_imputer,door_feature),
    ("num_imputer",num_imputer,numerical_feature)])

#TIME TO EXECUTE THINGS!!!